const IS_SERVER = typeof window === "undefined";
const CLIENT_MESSAGE = "ONLY AVAILABLE ON SERVER.";
export const CLIENT_ENTRY = IS_SERVER ? '{{SAMBELL_CLIENT_ENTRY}}' : CLIENT_MESSAGE; // happens post build
export const CLIENT_CHUNKS = IS_SERVER ? JSON.parse('{{SAMBELL_CLIENT_CHUNKS}}') : CLIENT_MESSAGE;
export const CLIENT_OUTPUT_DIR = IS_SERVER ? SAMBELL_CLIENT_OUTPUT_DIR : CLIENT_MESSAGE;
export const WEBPACK_MANIFEST = IS_SERVER ? '{{SAMBELL_WEBPACK_INLINE_MANIFEST}}' : null;
export const WEBPACK_PUBLIC_PATH = IS_SERVER ? SAMBELL_PUBLIC_PATH : CLIENT_MESSAGE;

export const waitForChunks = count => IS_SERVER ? `window.__SAMBELL_WAIT_FOR_CHUNKS__=${count};` : CLIENT_MESSAGE;
